name: Parallelize Jobs 

on:
    push:
        branches:
            - main
    
    pull_request:

jobs:

    build-test-image:
        name: Building Image for Testing
        runs-on: ubuntu-latest

        permissions:
            packages: write 

        steps:
  
            - name: Setting up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub 
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to ghcr.io registry
              uses: docker/login-action@v3
              with: 
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Build and Push to GHCR 
              uses: docker/build-push-action@v6
              with: 
                # context: .
                # file: Dockerfile 
                push: true
                tags: ghcr.io/wvrmhat/finance-automation-tool:${{ github.run_id }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                platforms: linux/amd64 


    test-unit:
        name: Unit Testing 
        needs: [build-test-image]
        runs-on: ubuntu-latest 

        permissions:
            packages: read 
        
        steps:
            
            - name: login to ghcr.io registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Unit Testing in Docker 
              run: docker run --rm ghcr.io/wvrmhat/finance-automation-tool:"$GITHUB_RUN_ID" echo "Run test commands here"

    cve-scanning:
        name: Scanning image with Trivy
        needs: [build-test-image]
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: read 
            security-events: write 

        steps:
            - name: Checkout git repo 
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to ghcr.io registry
              uses: docker/login-action@v3
              with: 
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Pull image to scan
              run: docker pull ghcr.io/wvrmhat/finance-automation-tool:"$GITHUB_RUN_ID"

            - name: Running Trivvy for all CVEs (non-blocking)
              uses: aquasecurity/Trivy-action@master 
              with:
                image-ref: ghcr.io/wvrmhat/finance-automation-tool:${{ github.run_id }}
                format: table
                exit-code: 0

    building-final-image:
        name: Build Final Image 
        needs: [test-unit, cve-scanning]
        runs-on: ubuntu-latest 

        permissions:
            packages: write 
            pull-requests: write 

        steps: 

            - name: Set up QEMU 
              uses: docker/setup-qemu-action@v3 

            - name: Checkout repository
              uses: actions/checkout@v4 

            - name: Set up Docker Buildx 
              uses: docker/setup-buildx-action@v3 

            - name: Login to Docker Hub 
              uses: docker/login-action@v3 
              with: 
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to ghcr.io registry 
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Metadata for Final Image Build 
              id: docker_meta
              uses: docker/metadata-action@v5
              with:
                images: wvrmhat/finance-automation-tool,ghcr.io/wvrmhat/finance-automation-tool
                flavor: | 
                    latest=false
                tags: |
                    type=raw,value=main_test 

            - name: Docker Build and Push to GHCR and Docker Hub
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
                labels: ${{ steps.docker_meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha, mode=max
                platforms: linux/amd64,linux/arm64

        